spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

ai:
  server:
    base-url: ${AI_SERVER_BASE_URL:https://closing-ai-production.up.railway.app}
    timeout-seconds: 90