spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

storage:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_REGION:ap-northeast-2}