-- Closing 서비스의 최초 PostgreSQL 스키마
-- 기준: feature/#70-flyway-db-schema 브랜치의 JPA 엔티티

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    kakao_id VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    name VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    profile_image_url TEXT,
    deleted_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_kakao_id UNIQUE (kakao_id)
);

CREATE TABLE business_registrations (
    registration_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    business_number VARCHAR(255) NOT NULL,
    business_owner_name VARCHAR(255),
    business_open_date TIMESTAMP(6),
    business_close_date TIMESTAMP(6),
    close_planned_date DATE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_business_registrations PRIMARY KEY (registration_id),
    CONSTRAINT uq_business_registrations_user UNIQUE (user_id),
    CONSTRAINT uq_business_registrations_number UNIQUE (business_number),
    CONSTRAINT fk_business_registrations_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE support_info (
    support_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    organization_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    apply_start_date DATE,
    apply_end_date DATE,
    application_period VARCHAR(255),
    external_id VARCHAR(255),
    external_url TEXT,
    status VARCHAR(255) NOT NULL DEFAULT 'ONGOING',
    view_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_support_info PRIMARY KEY (support_id),
    CONSTRAINT uq_support_info_external_id UNIQUE (external_id),
    CONSTRAINT ck_support_info_status
        CHECK (status IN ('ONGOING', 'CLOSED'))
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seller_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    business_category VARCHAR(255) NOT NULL,
    product_category VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    description TEXT,
    image_urls TEXT ARRAY,
    is_delivery_available BOOLEAN NOT NULL DEFAULT FALSE,
    is_direct_available BOOLEAN NOT NULL DEFAULT FALSE,
    trade_location VARCHAR(255),
    status VARCHAR(255) NOT NULL DEFAULT 'SELLING',
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    purchased_at DATE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT fk_products_seller
        FOREIGN KEY (seller_id) REFERENCES users (user_id),
    CONSTRAINT ck_products_business_category CHECK (
        business_category IN (
            'KOREAN_MEAL',
            'CHICKEN_PUB_BBQ',
            'CHINESE_HIGH_HEAT_KITCHEN',
            'JAPANESE_WESTERN',
            'DESSERT_CAFE_PACKAGE',
            'TAKEOUT_SPECIALTY',
            'BAKERY_EQUIPMENT',
            'OFFICE_FURNITURE_SET',
            'ACADEMY_STUDY_ROOM_EQUIPMENT',
            'HAIR_SALON_BARBERSHOP',
            'NAIL_SKINCARE_SALON',
            'GYM_PILATES',
            'CLOTHING_UNMANNED_STORE'
        )
    ),
    CONSTRAINT ck_products_product_category CHECK (
        product_category IN (
            'REFRIGERATOR_FREEZER',
            'DISHWASHER_FRYER',
            'SINK_WORKTABLE',
            'ICE_MAKER_SHOWCASE',
            'COMMERCIAL_TABLE',
            'LIGHTING_STORE_CABINET',
            'CHAIR_SOFA_BAR_CHAIR',
            'OFFICE_DESK_CHAIR',
            'DISHWARE_TABLEWARE_CONSUMABLES',
            'HEATING_COOLING_APPLIANCE',
            'POS_KIOSK_BILL_PRINTER'
        )
    ),
    CONSTRAINT ck_products_status
        CHECK (status IN ('SELLING', 'SOLD_OUT', 'DELETED', 'RESERVED'))
);

CREATE TABLE terms (
    term_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL,
    version VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    effective_date DATE NOT NULL,
    is_required BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_terms PRIMARY KEY (term_id),
    CONSTRAINT ck_terms_type
        CHECK (type IN ('SERVICE', 'PRIVACY', 'AGE'))
);

CREATE TABLE ai_sessions (
    session_id VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    messages TEXT NOT NULL,
    turn_count INTEGER NOT NULL,
    generated_tasks TEXT,
    confirmed_task_ids TEXT,
    version BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_ai_sessions PRIMARY KEY (session_id),
    CONSTRAINT ck_ai_sessions_status
        CHECK (status IN ('NEW', 'GENERATED', 'ALREADY_CONFIRMED'))
);

CREATE TABLE tasks (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    registration_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    start_date DATE,
    end_date DATE,
    start_time TIME(6),
    end_time TIME(6),
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    source VARCHAR(255) NOT NULL DEFAULT 'MANUAL',
    description TEXT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT pk_tasks PRIMARY KEY (task_id),
    CONSTRAINT fk_tasks_registration
        FOREIGN KEY (registration_id)
        REFERENCES business_registrations (registration_id),
    CONSTRAINT ck_tasks_source
        CHECK (source IN ('AI_GENERATED', 'MANUAL'))
);

CREATE TABLE inquiries (
    inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    image_urls TEXT ARRAY,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    answer TEXT,
    answered_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    CONSTRAINT pk_inquiries PRIMARY KEY (inquiry_id),
    CONSTRAINT fk_inquiries_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_inquiries_status
        CHECK (status IN ('PENDING', 'ANSWERED'))
);

CREATE TABLE chat_rooms (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_chat_rooms PRIMARY KEY (room_id),
    CONSTRAINT uq_chat_rooms_product_buyer UNIQUE (product_id, buyer_id),
    CONSTRAINT fk_chat_rooms_product
        FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT fk_chat_rooms_buyer
        FOREIGN KEY (buyer_id) REFERENCES users (user_id),
    CONSTRAINT fk_chat_rooms_seller
        FOREIGN KEY (seller_id) REFERENCES users (user_id)
);

CREATE TABLE chat_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    message_type VARCHAR(255) NOT NULL DEFAULT 'TEXT',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_chat_messages PRIMARY KEY (message_id),
    CONSTRAINT fk_chat_messages_room
        FOREIGN KEY (room_id) REFERENCES chat_rooms (room_id),
    CONSTRAINT fk_chat_messages_sender
        FOREIGN KEY (sender_id) REFERENCES users (user_id),
    CONSTRAINT ck_chat_messages_type
        CHECK (message_type IN ('TEXT', 'IMAGE'))
);

CREATE INDEX idx_chat_messages_room
    ON chat_messages (room_id, message_id);

CREATE TABLE product_bookmarks (
    bookmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_product_bookmarks PRIMARY KEY (bookmark_id),
    CONSTRAINT uq_product_bookmarks_user_product UNIQUE (user_id, product_id),
    CONSTRAINT fk_product_bookmarks_product
        FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT fk_product_bookmarks_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE bookmarks (
    bookmark_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    support_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    CONSTRAINT pk_bookmarks PRIMARY KEY (bookmark_id),
    CONSTRAINT uq_bookmarks_user_support UNIQUE (user_id, support_id),
    CONSTRAINT fk_bookmarks_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_bookmarks_support
        FOREIGN KEY (support_id) REFERENCES support_info (support_id)
);

CREATE TABLE user_terms (
    user_term_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    term_id BIGINT NOT NULL,
    agreed_at TIMESTAMP(6),
    CONSTRAINT pk_user_terms PRIMARY KEY (user_term_id),
    CONSTRAINT uq_user_terms_user_term UNIQUE (user_id, term_id),
    CONSTRAINT fk_user_terms_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_terms_term
        FOREIGN KEY (term_id) REFERENCES terms (term_id)
);
